server:
  build: ./server
  links:
    - "database:mysql"
  ports:
    - "8080:80"
  
database:
  image: mysql
  volumes:
    - ./database/data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=operationthunderinghammer
    - MYSQL_DATABASE=humhub
    - MYSQL_USER=humhub
    - MYSQL_PASSWORD=skfvbskbfiuryf943y9ytughushiuwg792